# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image-service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13image-service.proto\x12\rimage_service\"\x1c\n\x0eRecycleRequest\x12\n\n\x02id\x18\x01 \x01(\t\"/\n\x0fRecycleResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0c\n\x04type\x18\x02 \x01(\t2S\n\x05Image\x12J\n\x07Recycle\x12\x1d.image_service.RecycleRequest\x1a\x1e.image_service.RecycleResponse\"\x00\x42\x13Z\x11\x63sc2012-t12/protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\021csc2012-t12/proto'
  _RECYCLEREQUEST._serialized_start=38
  _RECYCLEREQUEST._serialized_end=66
  _RECYCLERESPONSE._serialized_start=68
  _RECYCLERESPONSE._serialized_end=115
  _IMAGE._serialized_start=117
  _IMAGE._serialized_end=200
# @@protoc_insertion_point(module_scope)
