version: '3'

services:
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - image-service
    networks:
      - app-network
    env_file:
      - route-map.env

  user-service:
    build: ./user-service
    ports:
      - "50051:50051"
    networks:
      - app-network
    env_file:
      - route-map.env

  image-service:
    build: ./image-service
    ports:
      - "50052:50052"
    networks:
      - app-network
    env_file:
      - route-map.env
    devices:
      - /dev/bus/usb:/dev/bus/usb

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    expose:
      - "3000"
    networks:
      - app-network
    env_file:
      - route-map.env
    restart: always

networks:
  app-network:
    driver: bridge
